name: "sashimi_tanpopo_action"
description: "Action for running sashimi_tanpopo with GitHub Actions"

inputs:
  ruby-version:
    description: |
      Runtime ruby version.
      This passed to ruby-version of ruby/setup-ruby.
      c.f. https://github.com/ruby/setup-ruby
    required: true
    default: ruby

  sashimi-tanpopo-version:
    description: |
      sashimi_tanpopo version. (e.g. 0.1.0, 0.1.1)
      default is latest.
      c.f. https://github.com/sue445/sashimi_tanpopo/releases
    required: false
    default: ""

  sashimi-tanpopo-command:
    description: |
      sashimi_tanpopo command. (e.g. local, github, gitlab)
      c.f. https://github.com/sue445/sashimi_tanpopo#usage
    required: true
    default: github

  sashimi-tanpopo-arguments:
    description: |
      sashimi_tanpopo arguments.
      c.f. https://github.com/sue445/sashimi_tanpopo#usage
    required: false
    default: ""

runs:
  using: composite

  steps:
    - name: Setup ruby
      uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
      with:
        ruby-version: ${{ inputs.ruby-version }}

    - name: Install sashimi_tanpopo
      run: |
        if [ ${SASHIMI_TANPOPO_VERSION} != "" ]; then
          args="--version ${SASHIMI_TANPOPO_VERSION}"
        fi
        gem install --no-doc sashimi_tanpopo ${args}
      shell: bash
      env:
        SASHIMI_TANPOPO_VERSION: ${{ inputs.sashimi-tanpopo-version }}

    - name: Run sashimi_tanpopo
      run: sashimi_tanpopo ${{ inputs.sashimi-tanpopo-command }} ${{ inputs.sashimi-tanpopo-arguments }}
      shell: bash
