name: Update Major Release Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  movetag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Extract Major Version and Update Tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/} 
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1) 

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git tag -d $MAJOR_VERSION || true 
          git push origin :refs/tags/$MAJOR_VERSION || true

          git tag $MAJOR_VERSION $VERSION          
          git push origin $MAJOR_VERSION

      - name: Log Tags
        run: |
          echo "Updated tag $MAJOR_VERSION to point to $VERSION"

      - name: Slack Notification (not success)
        uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d # v2.1.0
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
