name: test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run sashimi_tanpopo (Use latest version)
        uses: ./
        with:
          sashimi-tanpopo-command: version

      - name: Run sashimi_tanpopo (Use specified version)
        uses: ./
        with:
          sashimi-tanpopo-command: version
          sashimi-tanpopo-version: 0.1.0

      - name: Slack Notification
        uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d # v2.1.0
        if: always()
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
